import { 
    LuDollarSign,
    LuFilm,
    LuHouse,
    LuRadioTower,
    LuCarFront,
    LuAlbum,
    LuCat,
    LuCodeXml,
    LuCoffee,
    LuCross,
    LuDumbbell,
    LuFlower,
    LuGamepad2,
    LuMonitor,
    LuMusic4,
    LuPackage,
    LuPalette,
    LuPhone,
    LuPlane,
    LuPiggyBank,
    LuMail,
    LuHeart,
    LuHeartCrack,
    LuGlobe,
    LuGem,
    LuBell,
    LuALargeSmall,
    LuBlocks,
    LuGift,
    LuSend,

} from "react-icons/lu";


export const Icons = {
    1: <LuSend/>,
    2: <LuDollarSign/>,
    3: <LuFilm/>,
    4: <LuHouse/>,
    5: <LuRadioTower/>,
    6: <LuCarFront/>,
    7: <LuAlbum/>,
    8: <LuCat/>,
    9: <LuCodeXml/>,
    10: <LuCoffee/>,
    11: <LuCross/>,
    12: <LuDumbbell/>,
    13: <LuFlower/>,
    14: <LuGamepad2/>,
    15: <LuMonitor/>,
    16: <LuMusic4/>,
    17: <LuPackage/>,
    18: <LuPalette/>,
    19: <LuPhone/>,
    20: <LuPlane/>,
    21: <LuPiggyBank/>,
    22: <LuMail/>,
    23: <LuHeart/>,
    24: <LuHeartCrack/>,
    25: <LuGlobe/>,
    26: <LuGem/>,
    27: <LuBell/>,
    28: <LuALargeSmall/>,
    29: <LuBlocks/>,
    30: <LuGift/>,
}